/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation 

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').Sidebarsconfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  mainSidebar: [
    'main/intro',
    'main/features',
    'main/highlights',
    'main/requirements',
    'main/specs',
    'main/setup',
    'main/controller',
    'main/updating',
    'main/reference',
    'main/faq',
    'main/support',
    'main/credits',
  ],
  gallerySidebar: [
    'gallery/userinterface',
    'gallery/characters',
    'gallery/creatures',
    'gallery/armor',
    'gallery/mojavewasteland',
    'gallery/strip',  
    'gallery/capitalwasteland',
    'gallery/megaton',
    'gallery/drywells',
    'gallery/lakehavasu',
    'gallery/ziontrail',
    'gallery/arroyocanyon',
    'gallery/deadmoney',
    'gallery/honesthearts',
    'gallery/lonesomeroad',
    'gallery/oldworldblues',
    'gallery/anchorage',
    'gallery/pitt',
    'gallery/pointlookout',
    'gallery/mothershipzeta',
    'gallery/brokensteel',
    'gallery/casinointeriors',
    'gallery/houseinteriors',
    'gallery/industrialinteriors',
    'gallery/bunkerinteriors',
    'gallery/undergroundinteriors',
    'gallery/deadmoneyinteriors',
    'gallery/oldworldbluesinteriors',
    'gallery/anchorageinteriors',
    'gallery/pittinteriors',
  ],
  resourcesSidebar: [
   'resources/overview',
   'resources/links',
   'resources/lossless',
   'resources/stars',
   'resources/sweetloadorder',
   'resources/sweetrecommendedmods',
   'resources/troubleshooting',
  ],
  changelogSidebar: [
    'changelog/1.0.0.0',
  ],
};

export default sidebars;
